sudo: required
services:
  - docker

before_install:
  - docker build -t turdubars/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true turdubars/docker-react npm run test -- --coverage
